[project]
name = "knitting-machine"
version = "0.1.0"
description = "Tricking a Brother knitting machine into thinking that a computer is a disk drive"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
